[CodeStyle] Relocate functions

diff --git a/src/elfcheck b/src/elfcheck
--- a/src/elfcheck
+++ b/src/elfcheck
@@ -107,85 +107,6 @@ echof_info_size()
 
 ###############################################################################
 
-# Disassembly and show ASM code of a function (-d)
-
-disassembly()
-{
-    FUNCTION=$1
-    if [[ ! -n $FUNCTION ]]; then
-        echo ""
-        echo "You need to specify a function to disassembly (i.e. main)"
-        echo ""
-        exit 1
-    fi
-
-    RESULT=$(arm-none-eabi-objdump -d $FILE_ELF -C --disassemble="${FUNCTION}")
-    echo "$RESULT" | grep -e "<${FUNCTION}>:" > /dev/null 2>&1
-    if [[ $? != 0 ]]; then
-        echo ""
-        echo "Function \"${FUNCTION}\" not found in ELF."
-        echo ""
-        exit 1
-    fi
-    echo "$RESULT"
-    echo ""
-}
-
-###############################################################################
-
-# Show Common Dynamic Memory Functions Used (-x)
-
-check_dynamic_memory_function()
-{
-    echo ""
-    echo "Detected functions related to dynamic memory usage:"
-    echo ""
-    RESULT=$(\
-        arm-none-eabi-objdump -d $FILE_ELF -C \
-        | grep -E ' <malloc>:| <calloc>:| <realloc>:| <free>:|'\
-' <new>:| <delete>:|'\
-' <_malloc_r>:| <_calloc_r>:| <_realloc_r>:| <_free_r>:| <_Bfree>:'
-    )
-    if [[ $? != 0 ]]; then
-        echo "None"
-    else
-        echo "${RESULT}"
-    fi
-    echo ""
-}
-
-###############################################################################
-
-# Show memory size of requested component (-s)
-
-size_of_component()
-{
-    COMPONENT=$1
-    if [[ ! -n $COMPONENT ]]; then
-        echo ""
-        echo "You need to specify a component to check (i.e. main.cpp)"
-        echo ""
-        exit 1
-    fi
-
-    COMPONENT_INFO=$(arm-none-eabi-nm  -l --size-sort -t dec $FILE_ELF \
-                    | grep -i " t .*${COMPONENT}:")
-    if [[ $? != 0 ]]; then
-        echo ""
-        echo "Component \"${COMPONENT}\" not found in ELF."
-        echo ""
-        exit 1
-    fi
-
-    SIZE=$(echo "${COMPONENT_INFO}" | cut -d ' ' -f 1 \
-            | awk '{total += $0} END{print total}')
-    echo ""
-    echo "Size of $COMPONENT: $SIZE Bytes"
-    echo ""
-}
-
-###############################################################################
-
 # Analyse and export ELF info to output files (-a)
 
 analysis()
@@ -347,6 +268,85 @@ analysis()
     echo ""
     echo "Analysis completed"
     echo "Check output files from ${DIR_OUT_ANALYSIS} directory"
+    echo ""
+}
+
+###############################################################################
+
+# Disassembly and show ASM code of a function (-d)
+
+disassembly()
+{
+    FUNCTION=$1
+    if [[ ! -n $FUNCTION ]]; then
+        echo ""
+        echo "You need to specify a function to disassembly (i.e. main)"
+        echo ""
+        exit 1
+    fi
+
+    RESULT=$(arm-none-eabi-objdump -d $FILE_ELF -C --disassemble="${FUNCTION}")
+    echo "$RESULT" | grep -e "<${FUNCTION}>:" > /dev/null 2>&1
+    if [[ $? != 0 ]]; then
+        echo ""
+        echo "Function \"${FUNCTION}\" not found in ELF."
+        echo ""
+        exit 1
+    fi
+    echo "$RESULT"
+    echo ""
+}
+
+###############################################################################
+
+# Show memory size of requested component (-s)
+
+size_of_component()
+{
+    COMPONENT=$1
+    if [[ ! -n $COMPONENT ]]; then
+        echo ""
+        echo "You need to specify a component to check (i.e. main.cpp)"
+        echo ""
+        exit 1
+    fi
+
+    COMPONENT_INFO=$(arm-none-eabi-nm  -l --size-sort -t dec $FILE_ELF \
+                    | grep -i " t .*${COMPONENT}:")
+    if [[ $? != 0 ]]; then
+        echo ""
+        echo "Component \"${COMPONENT}\" not found in ELF."
+        echo ""
+        exit 1
+    fi
+
+    SIZE=$(echo "${COMPONENT_INFO}" | cut -d ' ' -f 1 \
+            | awk '{total += $0} END{print total}')
+    echo ""
+    echo "Size of $COMPONENT: $SIZE Bytes"
+    echo ""
+}
+
+###############################################################################
+
+# Show Common Dynamic Memory Functions Used (-x)
+
+check_dynamic_memory_function()
+{
+    echo ""
+    echo "Detected functions related to dynamic memory usage:"
+    echo ""
+    RESULT=$(\
+        arm-none-eabi-objdump -d $FILE_ELF -C \
+        | grep -E ' <malloc>:| <calloc>:| <realloc>:| <free>:|'\
+' <new>:| <delete>:|'\
+' <_malloc_r>:| <_calloc_r>:| <_realloc_r>:| <_free_r>:| <_Bfree>:'
+    )
+    if [[ $? != 0 ]]; then
+        echo "None"
+    else
+        echo "${RESULT}"
+    fi
     echo ""
 }
 
